- name: run a docker container
  hosts: localhost
  become: false
  tasks:
    - name: Ensure pip is installed
      ansible.builtin.dnf:
          name: python3-pip
          state: present
      become: yes

    - name: Install Docker SDK and pin requests version
      ansible.builtin.pip:
        name:
          - docker
          - "requests<2.32.0"
        state: present
        executable: pip3
      become: yes

    - name: Create a data container
      community.docker.docker_container:
        name: "{{ item }}"
        image: pavanidevops78/kubernetes:runner
        state: started
        recreate: true
        privileged: true
        env:
          URL: "{{ URL }}"
          TOKEN: "{{ TOKEN }}"
          NAME: "{{ item }}"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
      loop:
        - runner1
        - runner2
        - runner3
