- name: run a docker container
  hosts: localhost
  become: false
  tasks:
    - name: install python requests
      ansible.builtin.pip:
        name: docker
        state: present
        executable: pip3.9
        become: yes

    - name: install python requests
      ansible.builtin.pip:
        name: requests
        version: "<2.32.0"
        state: present
      executable: pip3.9
      become: yes

    - name: install python-docker
      ansible.builtin.dnf:
        name: python3-docker

    - name: Create a data container
      community.docker.docker_container:
        name: "{{ item }}"
        image: pavanidevops78/kubernetes:runner
        state: started
        recreate: true
        env:
          URL: "{{ URL }}"
          TOKEN: "{{ TOKEN }}"
          NAME: "{{ item }}"
      loop:
        - runner1
        - runner2
        - runner3
